language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.6

notifications:
  email:
    recipients:
      - mide.ojikutu@gmail.com
script: sbt cassandra-connector4s/test && sbt cassandra-connector4s-scalatra-example/test